# Generated by Django 4.0.1 on 2022-01-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_remove_movie_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(null=True),
        ),
    ]
